### PR TITLE
Setup tests, linting and codestyle checks

### PR DESCRIPTION
**Pull request by thijskramer**
This PR adds linting with Ruff, codestyle checks with black and a setup for testing with pytest.

The tests themselves are being written.

### CODE REVIEW

**Comment by Niicck** [comment]
Hi! Do you need any help with getting this PR finished?

I'm about to start another attempt at getting multi-configs to work (see: https://github.com/MrBin99/django-vite/pull/50). Having linting and testing in place beforehand would make that feel a lot safer.

**Comment by thijskramer** [comment]
Yes, help would be much appreciated! The reason I started writing tests was for the exact same reason: to feel much safer during refactoring.

**Comment by Niicck** [comment]
Cool, I got a PR into this branch that adds 100% Testing Coverage (https://github.com/MrBin99/django-vite/pull/91). I appreciate you putting the whole testing framework into place.

**Comment by thijskramer** [comment]
> Cool, I got a PR into this branch that adds 100% Testing Coverage (#91). I appreciate you putting the whole testing framework into place.

Thank you very much for your efforts! I've merged your PR into this one. I'll merge this into `master` so that future pull requests will be tested.

**Comment by Niicck** [comment]
Awesome, thanks for merging that in. I'm working on a refactor that'll allow us to use multiple vite app configurations. That'll be up soon.

**Pull request merged**
