### PR TITLE
Added config mechanism for running multiple vue apps (on different ports)

### PR DESCRIPTION
**Pull request by vivazzi**
I think this pull request does not cover all scenario of config (fixes cover my needs in real project). If you like new feature I can add all config scenario with your help and I can add new commt to my pull request. Also I can add description of new functionality to README file.

I added DJANGO_VITE variable to add constants `DJANGO_VITE_DEV_SERVER_PORT`, `DJANGO_VITE_MANIFEST_PATH`, `DJANGO_VITE_STATIC_URL_PREFIX`, `DJANGO_VITE_DEV_MODE` as default. So if you use one configuration, you can use these constants as usually.

By default, DJANGO_VITE is:

```
DJANGO_VITE = getattr(
    settings, "DJANGO_VITE", {
        'default': {
            'port': DJANGO_VITE_DEV_SERVER_PORT,
            'manifest_path': DJANGO_VITE_MANIFEST_PATH,
            'static_url_prefix': DJANGO_VITE_STATIC_URL_PREFIX,
            'dev_mode': DJANGO_VITE_DEV_MODE,
        }
    }
)
```

But if you want use different configs you need add `DJANGO_VITE` to your `settings.py` file. For example:

```
DJANGO_VITE = getattr(
    settings, "DJANGO_VITE", {
        'default': {
            'port': 3000,
            'manifest_path': 'path_to_config_1',
            'static_url_prefix': 'url_prefix_1',
            'dev_mode': True,
        },
         'config_2': {
            'port': 3001,
            'manifest_path': 'path_to_config_1',
            'static_url_prefix': 'url_prefix_2',
            'dev_mode': False,
        }
    }
)
```

In template we can use like that for `config_2`:

```
{% vite_hmr_client config='config_2' %}
{% vite_asset 'app/main.js' config='config_2' %}
```

or without parameter config (in this case config will has 'default' name by default):

```
{% vite_hmr_client %}
{% vite_asset 'app/main.js' %}
```

Also you can pass dict object to config parameter. Dict must have all required fields, for example:

```
# views.py
def my_view(request):
    config = {
        'manifest_path': 'path_to_config_3',
        'port': 3002,
        'dev_mode': False,
        'static_url_prefix': 'url_prefix_3',
    },
    return render(request, 'template.html', {'config': config})

# template.html
{% vite_hmr_client config=config %}
{% vite_asset 'app/main.js' config=config %}
```

This is useful if you write own package. And some projects use your package. This eliminates the need to write your package config in settings.py of projects (config package will be inside of your package).

### CODE REVIEW

**Comment by vivazzi** [comment]
I am glad to your answer!
Then you need define what it is required else to add.

Some questions:
1. Does my solution match the architecture of the library? I think we need stay all constants as is. And we can add `DJANGO_VITE` constant as optional. About it I discribed above. I think simple name `DJANGO_VITE` would be appropriate.
2. We have constants:
  1. DJANGO_VITE_DEV_MODE
  2. DJANGO_VITE_DEV_SERVER_PROTOCOL
  3. DJANGO_VITE_DEV_SERVER_HOST
  4. DJANGO_VITE_DEV_SERVER_PORT
  5. DJANGO_VITE_WS_CLIENT_URL
  6. DJANGO_VITE_ASSETS_PATH
  7. DJANGO_VITE_STATIC_URL_PREFIX
  8. DJANGO_VITE_STATIC_ROOT
  9. DJANGO_VITE_MANIFEST_PATH
  10. DJANGO_VITE_LEGACY_POLYFILLS_MOTIF

Now, 4 from 10 is in `DJANGO_VITE`. I think it is need add more constants. And we need what we want to add to `DJANGO_VITE` (Moreover, these parameters will be apparently optional). We need have flexible config to cover all scenarios.

3. Who can fix README to add new functionality?

I can solve these questions (or some of them) myself and add commits to this PR if you do not have time for this project

**Comment by MrBin99** [comment]
Thanks for your PR !
I was thinking maybe merging your PR and dropping the old way of setting configurations (with multiple variables) and making a major version.

I think your solution is great and everybody should use it that way because Django configuration works that way when you configure your database for example.

What do you think ?

**Comment by vivazzi** [comment]
@MrBin99 your decision is good, but it breaks compatibility. Are we ready to it? And I think we can must standardize this. At least each developer can use uscually (for example, looks like db option). I can rewrite code and documantation to use looks like as DB option. Now I am in interesting project, but I try to find time to finish our work.

**Comment by vivazzi** [comment]
I will add a new commits to this PR. Can you check my commits? I have not enough experience to influence to big project like your "django-vite"

**Comment by vivazzi** [comment]
Yes, I am agree that my initial idea may be more flexibily but has more complex (in configurations) and not enough clear. And if you create other PR and we can discuss this question and compare more visually - it is good idea!

**Comment by MrBin99** [comment]
Hi,
I've opened a pull-request, feel free to comment and review ! #50

**Pull request closed without merging**
